### ISSUE TITLE
ActionView::MissingTemplate

### ISSUE THREAD

**Issue by Felipedelima123** [richardrails/ransack_memory#1]
Hey Richard thanks for developing this, It really help me. 
So I followed the instructions on the docs, but if I try to use the <%= clear_filter %> helper, I have the error bellow:

![image](https://user-images.githubusercontent.com/20612175/40866770-0359d110-65d6-11e8-88d3-dee7bf272913.png)

So, look in the code of the gem, I see that the partial is in HAML file and I am using the ERB extension by default here:

https://github.com/richardrails/ransack_memory/blob/master/app/views/shared/_ransack_memory_clear_filter.html.haml

So, for solve it I just used the code direct in the link_to tag, ass bellow:

<%= link_to RansackMemory::Core.config[:link_label].presence || 'Clear filter', url_for + "?cancel_filter=true" %>

Also, I am creating a Merge Request, adding the file _ransack_memory_clear_filter.html.erb with the right solution.

**Comment by richardrails** [comment]
Thank you for the pull request. It has been merged into master. I have also make new minor version of the gem.
