### ISSUE TITLE
save_and_load_filters() always creates params[:q]

### ISSUE THREAD

**Issue by lobin-z0x50** [richardrails/ransack_memory#10]
Hello, I've verified that I have this library installed into my product, but I'm having an issues.

The method `save_and_load_filters()` always creates `params[:q]` even if the parameter `q` is not actually specified.
  https://github.com/richardrails/ransack_memory/blob/master/app/controllers/concerns/ransack_memory/concern.rb#L36

If the HTTP request does not contain the parameter `q`, now `params[:q]` will be set to `nil`. I'm in trouble because `params.fetch(:q, {})` returns `nil`.
If the HTTP request does not contain the parameter `q`, it would be better if the key` q` does not exist in `params`. then I think `params.fetch(:q, {})` returns `{}`.

**Comment by lobin-z0x50** [comment]
I'm sorry, it was a mistake.
It should be as follows.

-----
The method `save_and_load_filters()` always creates `params[:q]` even if the `session[:q]` is not actually exists.

If `session[:q]` does not exists, now `params[:q]` will be set to nil. I'm in trouble because `params.fetch(:q, {})` returns `nil`.
If `session[:q]` does not exists, it would be better if the key `:q` does not exist in `params`. then I think `params.fetch(:q, {})` returns `{}`.

**Comment by richardrails** [comment]
thank you for your fix. It is merged
