### ISSUE TITLE
"can't dump IO" error with Rails 7 when using cache as session store

### ISSUE THREAD

**Issue by ukdave** [richardrails/ransack_memory#12]
Firstly, thanks so much for this gem!

I have found an issue after upgrading to Rails 7 when the session store configured to use the rails cache, e.g:

```ruby
config.cache_store = :redis_cache_store, { url: ENV['REDIS_URL'] }
config.session_store :cache_store, key: "_some_session_key"
```

When hitting a controller action with a ransack query parameter I am getting a `can't dump IO` error from within the ActiveSupport cache code where it is attempting to serialise the session:

```ruby
# activesupport (7.0.2.2) lib/active_support/cache.rb

974     when nil, true, false, Numeric
975       uncompressed_size = 0
976     when String
977       uncompressed_size = @value.bytesize
978     else
979       serialized = Marshal.dump(@value)  # <<< error occurs here
980       uncompressed_size = serialized.bytesize
981     end
982     if uncompressed_size >= compress_threshold
983       serialized ||= Marshal.dump(@value)

# >> @value
# => {"_csrf_token"=>"bwmQ57IaBiDL8bp0baLYNSt0imbdJh8LtwO6Mn-kpe0", "ranmemory_users_index_html"=>#<ActionController::Parameters {"name_eq"=>"bob"} permitted: true>, "last_q_params"=>#<ActionController::Parameters {"name_eq"=>"bob"} permitted: true>}
```

The issue appears to be caused by trying to serialise the `ActionController::Parameters` objects, and can be fixed by storing params in the session as a hash instead.

**Comment by richardrails** [comment]
have you tested your changes with older rails?

**Comment by ukdave** [comment]
Yes, I've tested my fix with Rails 6.1 as well didn't see any issues.

**Comment by richardrails** [comment]
Ok i merge it

**Comment by richardrails** [comment]
thank you for your PR

**Comment by ukdave** [comment]
that's great, thanks :)

**Comment by nbluis** [comment]
Hi @richardrails and @ukdave.

This fix is already released to the rubygems ?

The last release I found in RubyGems are [0.0.9] from March 11, 2020.

If not, can you relase a new version of the gem ? 🥺
