### ISSUE TITLE
how does the "It also autoloads params from session to your search forms." work?

### ISSUE THREAD

**Issue by StandardNerd** [richardrails/ransack_memory#3]
I have a Ransack search form like this:

    <%= search_form_for @search do |f| %>
      <%= f.grouping_fields(f.object.new_grouping) do |g| %>
        <%= g.condition_fields(g.object.new_condition) do |c| %>
          <%= c.attribute_fields do |a| %>
            <%= a.attribute_select %>
          <% end %>
          <%= c.predicate_select only: %i(cont not_eq eq) %>
          <%= c.value_fields do |v| %>
            <%= v.text_field :value %>
          <% end %>
        <% end %>
      <% end %>
      <%= f.submit "filter" %>
    <% end %>

The autoloading of search params from session doesn't work with this form. How can I fix so that the selected search params are displayed with the results?

**Comment by richardrails** [comment]
I think it is not working with dynamic ransacker. This gem only saves params[:q] into session.

**Comment by StandardNerd** [comment]
ah ok. Thanks for the quick reply!
